# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_cli.ipynb.

# %% auto 0
__all__ = ['sidecar_cli', 'aggregate_cli', 'accumulator_cli', 'finalize_cli', 'to_geoparquet_cli']

# %% ../nbs/05_cli.ipynb 1
"""Command-line interface for healpyxel."""

import sys

def sidecar_cli():
    """CLI entry point for healpix_sidecar command."""
    from healpyxel import sidecar
    return sidecar.main()

def aggregate_cli():
    """CLI entry point for healpix_aggregate command."""
    from healpyxel import aggregate
    return aggregate.main()

def accumulator_cli():
    """CLI entry point for healpix_accumulator command."""
    from healpyxel import accumulator
    return accumulator.main()

def finalize_cli():
    """CLI entry point for healpix_finalize command."""
    from healpyxel import finalize
    return finalize.main()

def to_geoparquet_cli():
    """CLI entry point for healpyxel_to_geoparquet command."""
    from healpyxel import geospatial
    return geospatial.main()
