project:
  type: website

format:
  html:
    logo: logo_cutout_128.png
    respect-user-color-scheme: true
    theme: 
      dark: superhero
      light: default
    # monobackgroundcolor: "#808080" 
    css: styles.css
    toc: true
    keep-md: true
    page-layout: full
    grid:
      body-width : 1400px
      sidebar-width: 250px
      margin-width: 200px
  commonmark: default

website:
  favicon : favicon.ico
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.html
      - text: "Quickstart"
        href: example_quickstart.html
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/mariodamore/healpyxel/
          - text: Report a Bug
            href: https://github.com/mariodamore/healpyxel/issues/new
  sidebar:
    style: floating
    logo: logo_cutout_128.png
    collapse-level: 1
    contents:
      - text: HealPyxel
        href: index.ipynb
      - section: Examples
        contents:
          - 80_example_quickstart.ipynb
          - 81_example_visualization_workflow.ipynb
          - 82_example_visualization_psf.ipynb
          - 83_example_accumulation.ipynb
          - 90_example_streaming.ipynb
      - section: API Reference
        contents:
        - 00_setup.ipynb
        - 01_sidecar.ipynb
        - 02_aggregate.ipynb
        - 03_accumulator.ipynb
        - 04_finalize.ipynb
        - 05_cli.ipynb
        - 06_visualization.ipynb
        - 07_geospatial.ipynb

metadata-files: [nbdev.yml]
